# Starter pipeline1233332222
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

resources:
- repo: self

variables:
- group: CICD

parameters:
  - name: tag
    default: "$(Build.BuildId)"
  - name: imageName
    default: "demo-page"

stages:
- stage: CICD
  displayName: CICD workflow
  jobs:
  - job: Build
    displayName: Build
    pool: local-agent

    steps:
      - script: |
          echo "La version configurada es: $(appVersion)"
        displayName: Comprobar la variable

      - task: Docker@2
        displayName: Build an image
        inputs:
          containerRegistry: 'registryConnection'
          repository: ${{ parameters.imageName }}
          command: 'build'
          dockerfile: '**/Dockerfile'
          tags: |
            $(tag)

      - task: AzureContainerApps@1
        displayName: Deploy to Azure Container App
        inputs:
          azureSubscription: 'appDeployConnection'
          imageToDeploy: '$(acrTarget)/${{ parameters.imageName }}:$(tag)'
          containerAppName: 'app-demo-page'
          resourceGroup: 'RG-jenkinsCaro'
          acrTarget: 'ACRAPPSCAROLINA.azurecr.io'
          acrUsername: $(acrUsername)
          acrPassword: $(acrPassword)